services:
  mariadb:
    image: mariadb:12.3.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb/mariadb_init:/docker-entrypoint-initdb.d:ro
      - mariadb_data:/var/lib/mysql
    ports:
      - 3307:3306
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  ##################################################################################

  app:
    build: . # Pfad zum Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  ##################################################################################

  phpmyadmin:
    image: phpmyadmin:5.2.3
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    restart: unless-stopped


volumes:
  mariadb_data:

##################################################################################

