### Todo erstellen

POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "text": "Rasen im Garten von Opa mähen"
}

### Alle Todos abrufen

GET http://localhost:8080/api/todos

### Einzelnes Todo abrufen

GET http://localhost:8080/api/todos/3

### Todo aktualisieren

PUT http://localhost:8080/api/todos/3
Content-Type: application/json

{
  "text": "Rasen im Garten und vor dem Haus von Opa mähen",
  "done": true
}

### Todo löschen

DELETE http://localhost:8080/api/todos/3

### game 

### Benutzer einloggen
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "houssea",
  "password": "19939382",

  "role" : "admin"
}